# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  congo = {
    pname = "congo";
    version = "v2.5.4";
    src = fetchFromGitHub ({
      owner = "jpanther";
      repo = "congo";
      rev = "v2.5.4";
      fetchSubmodules = false;
      sha256 = "sha256-Vk+F8c+1UpohcSJfqmctWJo8hhAasAK8mX28GAX0zOE=";
    });
  };
}
