# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  congo = {
    pname = "congo";
    version = "v2.6.1";
    src = fetchFromGitHub {
      owner = "jpanther";
      repo = "congo";
      rev = "v2.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-2A+aTr4Ozog128PADFHdQDnDIPquJCBlnZedZN/mZlA=";
    };
  };
}
